const A = "a".repeat(64);
const B = "b".repeat(64);
const C = "c".repeat(64);
const ETAG_A = `"${A}"`;
const ETAG_B = `"${B}"`;
const NOW = "2026-07-14T12:00:00Z";

const supportedAxis = { supported: true, reason_code: null, summary: null } as const;
const support = {
  overall: "supported",
  execution: supportedAxis,
  capture: supportedAxis,
  harness: supportedAxis,
  runtime: supportedAxis,
} as const;
const snapshot = (name: string, digest: string) => ({ snapshot_id: `${name}-snapshot-fixture-1`, digest });
const revision = {
  revision_id: "revision-fixture-1",
  generation: 1,
  manifest_digest: C,
  state: "active",
} as const;

export const CONTRACT_FIXTURE_V1 = {
  version: {
    schema_version: "1",
    api_name: "openevo-desktop-local-api",
    preferred_major: 1,
    supported_majors: [1],
    openapi_sha256: A,
    build_version: "1.0.0-test.1",
    source_commit: "dabbfec3",
    build_channel: "test",
    provider_kind: "contract_simulator",
    feature_flags: ["remote_profiles", "operation_events", "artifact_inspection", "maintenance"],
  },
  bootstrap: {
    schema_version: "1",
    endpoint: "http://127.0.0.1:43117",
    session_token: "fixture-desktop-session-token-0000000000000001",
    negotiated_contract: {
      major: 1,
      openapi_sha256: A,
      provider_kind: "contract_simulator",
      feature_flags: ["remote_profiles", "operation_events", "artifact_inspection", "maintenance"],
    },
  },
  health: {
    schema_version: "1",
    service: "openevo-desktop-sidecar",
    status: "ok",
    checked_at: NOW,
  },
  error: {
    schema_version: "1",
    request_id: "request-fixture-1",
    code: "project_not_ready",
    http_status: 409,
    message: "The project is not ready.",
    severity: "blocking",
    category: "project",
    retryable: true,
    repair_action: "openevo_can_retry",
    next_action: "Retry after project validation succeeds.",
    details: { resource_id: "project-fixture-1", retry_after_seconds: 1 },
    logs_ref: "logs-fixture-1",
  },
  unsupportedVersionError: {
    schema_version: "1",
    request_id: "request-fixture-426",
    code: "contract_version_unsupported",
    http_status: 426,
    message: "No compatible Desktop Local API version is available.",
    severity: "blocking",
    category: "contract",
    retryable: false,
    repair_action: "upgrade_required",
    next_action: "Update OpenEvo Desktop.",
    details: { supported_majors: [2], requested_majors: [1] },
    logs_ref: null,
  },
  cursorExpiredError: {
    schema_version: "1",
    request_id: "request-fixture-cursor",
    code: "event_cursor_expired",
    http_status: 410,
    message: "The event cursor has expired.",
    severity: "warning",
    category: "contract",
    retryable: true,
    repair_action: "openevo_can_retry",
    next_action: "Reload snapshots before reconnecting.",
    details: {},
    logs_ref: null,
  },
  profile: {
    schema_version: "1",
    profile_id: "profile-fixture-1",
    name: "Research GPU",
    host: "gpu.example.test",
    port: 22,
    user: "researcher",
    authentication_kind: "native_private_key",
    credential_slots: [
      { kind: "ssh_private_key", status: "stored", updated_at: NOW },
      { kind: "ssh_private_key_passphrase", status: "stored", updated_at: NOW },
    ],
    proxy: { http_url: "http://proxy.example.test:8080", https_url: null, no_proxy: ["localhost"] },
    connection_state: "connected",
    host_key_fingerprint: "SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    etag: ETAG_A,
    created_at: NOW,
    updated_at: NOW,
  },
  project: {
    schema_version: "1",
    project_id: "project-fixture-1",
    name: "Protein Design",
    profile_id: "profile-fixture-1",
    task: { title: "Design task", objective: "Produce and validate a candidate.", task_ref: null },
    source: { kind: "scratch", display_name: "New workspace", source_ref: null },
    execution: {
      mode: "self-deployed",
      capture_mode: "transcript",
      token_level_metrics_available: false,
      codex_model: null,
      managed_model_id: "managed-model-fixture-1",
    },
    evolution: {
      text_memory: { enabled: true, method: "reference_text_memory", config: { max_records: 100 } },
      skill_bundle: { enabled: false, method: null, config: {} },
    },
    state: "active",
    current_revision_id: "revision-fixture-1",
    etag: ETAG_B,
    created_at: NOW,
    updated_at: NOW,
  },
  operation: {
    schema_version: "1",
    operation_id: "operation-fixture-1",
    operation_kind: "bootstrap",
    state: "running",
    resource: { resource_type: "project", resource_id: "project-fixture-1" },
    progress: { current: 2, total: 4, label: "Verifying remote Core" },
    checks: [
      {
        check_id: "core.install",
        label: "Core installation",
        status: "passed",
        summary: "Verified installation is available.",
        repair_action: "none",
      },
    ],
    result: null,
    error: null,
    created_at: NOW,
    started_at: NOW,
    finished_at: null,
  },
  run: {
    schema_version: "1",
    run_id: "run-fixture-1",
    project_id: "project-fixture-1",
    state: "running",
    queued_reason: null,
    project_snapshot: snapshot("project", A),
    task_snapshot: snapshot("task", B),
    workspace_snapshot: snapshot("workspace", C),
    capability_registry_digest: B,
    pinned_revision: revision,
    successor_revision: {
      revision_id: "revision-fixture-2",
      generation: 2,
      manifest_digest: A,
      state: "preparing",
    },
    latest_attempt: {
      attempt_id: "attempt-fixture-1",
      number: 1,
      state: "running",
      started_at: NOW,
      finished_at: null,
    },
    created_at: NOW,
    updated_at: NOW,
    etag: ETAG_A,
    error: null,
  },
  timeline: {
    entry_id: "timeline-fixture-1",
    occurred_at: NOW,
    stage: "agent",
    state: "running",
    title: "Science task",
    summary: "The task is running against the pinned revision.",
    progress: null,
  },
  log: {
    log_id: "log-fixture-1",
    occurred_at: NOW,
    level: "info",
    source: "run",
    message: "Task execution started.",
    code: "task_started",
  },
  context: {
    schema_version: "1",
    run_id: "run-fixture-1",
    pinned_revision: revision,
    successor_revision: null,
    contributions: [
      {
        target_id: "text_memory",
        artifact_id: "artifact-memory-fixture-1",
        artifact_type: "text_memory",
        selected: true,
        summary: "Validated task memory.",
      },
    ],
  },
  artifacts: [
    {
      artifact_type: "text_memory",
      format: "markdown",
      artifact_id: "artifact-memory-fixture-1",
      target_id: "text_memory",
      display_name: "Task memory",
    },
    {
      artifact_type: "skill_bundle",
      skill_count: 1,
      artifact_id: "artifact-skill-fixture-1",
      target_id: "skill_bundle",
      display_name: "Analysis workflow",
    },
    {
      artifact_type: "agent_system",
      instruction_kind: "agents",
      artifact_id: "artifact-agent-fixture-1",
      target_id: "agent_system",
      display_name: "Agent instructions",
    },
    {
      artifact_type: "parametric_memory",
      release_enabled: false,
      adapter_id: "adapter-fixture-1",
      base_model_id: "fixture-model",
      adapter_format: "lora",
      artifact_id: "artifact-adapter-fixture-1",
      target_id: "parametric_memory",
      display_name: "Reserved adapter",
    },
  ].map((variant) => ({
    schema_version: "1",
    project_id: "project-fixture-1",
    run_id: "run-fixture-1",
    summary: "Deterministic artifact.",
    content_digest: A,
    byte_size: 128,
    lineage: { source_dataset_ids: ["dataset-fixture-1"], parent_artifact_ids: [], producing_job_id: "job-fixture-1" },
    compatibility: { execution_modes: ["self-deployed"], harness_ids: ["codex"], base_model_ids: [] },
    scores: [{ name: "quality", value: 0.8 }],
    selected: true,
    promoted: true,
    revision_ids: ["revision-fixture-2"],
    created_at: NOW,
    ...variant,
  })),
  artifactContent: {
    schema_version: "1",
    artifact_id: "artifact-memory-fixture-1",
    content_digest: A,
    documents: [
      { document_id: "memory", title: "Task memory", media_type: "text/markdown", content: "# Memory\n\nValidated behavior." },
    ],
  },
  artifactDiff: {
    schema_version: "1",
    artifact_id: "artifact-memory-fixture-1",
    base_artifact_id: null,
    hunks: [
      {
        hunk_id: "memory-hunk-1",
        heading: "Task memory",
        lines: [{ kind: "added", old_line: null, new_line: 1, text: "Validated behavior." }],
      },
    ],
    truncated: false,
  },
  service: {
    schema_version: "1",
    service_id: "service-core-fixture-1",
    display_name: "OpenEvo Core",
    kind: "core",
    state: "healthy",
    health_summary: "Core is ready.",
    restart_supported: true,
    observed_at: NOW,
  },
  diagnostic: {
    schema_version: "1",
    diagnostic_id: "diagnostic-fixture-1",
    status: "healthy",
    generated_at: NOW,
    checks: [
      { check_id: "core.readiness", label: "Core readiness", status: "passed", summary: "Core is ready.", repair_action: "none" },
    ],
    findings: [],
    etag: ETAG_B,
  },
  capabilities: {
    schema_version: "1",
    project_id: "project-fixture-1",
    execution_mode: "self-deployed",
    source: "verified_remote_core",
    registry_verified: true,
    registry_digest: B,
    core_version: "1.0.0",
    fetched_at: NOW,
    targets: [
      {
        target_id: "text_memory",
        display_name: "Text memory",
        description: "Natural-language memory.",
        artifact_type: "text_memory",
        release_enabled: true,
        configured_default_method_id: "reference_text_memory",
        effective_default_method_id: "reference_text_memory",
        methods: [
          {
            method_id: "reference_text_memory",
            display_name: "Reference text memory",
            description: "Reference implementation.",
            maturity: "stable",
            identity_digest: C,
            config_schema: { type: "object", additionalProperties: false, properties: {} },
            default_config: {},
            support,
          },
        ],
        accepted_methods: [{ method_id: "reference_text_memory", identity_digest: C, support }],
        selection_resolvers: [],
      },
    ],
  },
  validation: {
    schema_version: "1",
    project_id: "project-fixture-1",
    project_etag: ETAG_B,
    capability_registry_digest: B,
    valid: true,
    issues: [],
    validated_at: NOW,
  },
  state: {
    schema_version: "1",
    observed_at: NOW,
    contract: { selected_major: 1, desktop_openapi_sha256: A, core_openapi_sha256: B, compatible: true },
    core: { state: "core_ready", profile_id: "profile-fixture-1", active_tunnel: true, last_error_code: null },
    active_project: {
      project_id: "project-fixture-1",
      project_etag: ETAG_B,
      profile_id: "profile-fixture-1",
      connection_state: "ready",
    },
    pending_operation_ids: ["operation-fixture-1"],
  },
} as const;

export const PROFILE_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.profile],
  next_cursor: "profile-cursor-2",
  has_more: true,
} as const;
export const RUN_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.run],
  next_cursor: null,
  has_more: false,
} as const;
export const EVENT_FIXTURE_V1 = {
  schema_version: "1",
  event_id: "event-fixture-7",
  event_name: "desktop.v1.run.changed",
  occurred_at: NOW,
  sequence: 7,
  data: {
    kind: "run_changed",
    resource: { resource_type: "run", resource_id: "run-fixture-1" },
    change: "updated",
  },
} as const;
