const A = "a".repeat(64);
const B = "b".repeat(64);
const C = "c".repeat(64);
const ETAG_A = `"${A}"`;
const ETAG_B = `"${B}"`;
const NOW = "2026-07-14T12:00:00Z";
const OPENAPI_DIGEST = "26ee1e2b6b25f3297c5c09544a9a10ce95baae233ac4b3de2dc0f72cc32ad3cb";

export const RELEASE_EXECUTION_MODE_CAPABILITIES_FIXTURE_V1 = {
  schema_version: "1",
  modes: [
    {
      mode: "codex_subscription_transcript",
      display_name: "Subscription",
      support_state: "supported",
      reason_code: null,
      message: "Available in this OpenEvo Desktop release.",
    },
    {
      mode: "self-deployed",
      display_name: "Self-deployed",
      support_state: "unavailable",
      reason_code: "self_deployed_release_unavailable",
      message: "Self-deployed execution is not available in this OpenEvo Desktop release. Choose Subscription to save or run this project.",
    },
  ],
} as const;

const supportedAxis = {
  state: "supported",
  reason_code: null,
  message: "Supported.",
  missing_requirements: [],
} as const;
const support = {
  overall: "supported",
  execution: supportedAxis,
  capture: supportedAxis,
  harness: supportedAxis,
  runtime: supportedAxis,
} as const;
const snapshot = (kind: "project" | "task" | "workspace", digest: string) => ({
  id: `${kind}-snapshot-fixture-1`,
  kind,
  content_sha256: digest,
  created_at: NOW,
});
const activeRevision = {
  id: "revision-fixture-1",
  project_id: "project-fixture-1",
  generation: 1,
  manifest_sha256: C,
} as const;
const successorRevision = {
  id: "revision-fixture-2",
  project_id: "project-fixture-1",
  generation: 2,
  manifest_sha256: A,
} as const;
const requiredRevision = {
  revision: activeRevision,
  reachable_from_revision_id: activeRevision.id,
  relation: "active",
} as const;
const revisionTransition = {
  state: "running_methods",
  predecessor_revision: activeRevision,
  successor_revision: successorRevision,
  progress_completed: 1,
  progress_total: 4,
  message: "Evolution methods are running for the next revision.",
  error: null,
  updated_at: NOW,
} as const;
const attempt = {
  id: "attempt-fixture-1",
  run_id: "run-fixture-1",
  number: 1,
  status: "running",
  queued_reason: null,
  created_at: NOW,
  updated_at: NOW,
  started_at: NOW,
  finished_at: null,
  error: null,
} as const;
const runSummary = {
  id: "run-fixture-1",
  project_id: "project-fixture-1",
  project_snapshot: snapshot("project", A),
  task_snapshot: snapshot("task", B),
  workspace_snapshot: snapshot("workspace", C),
  registry_digest: B,
  execution_mode: "self-deployed",
  capture_mode: "transcript",
  status: "running",
  queued_reason: null,
  current_attempt_id: attempt.id,
  current_attempt: attempt,
  attempt_count: 1,
  current_error: null,
  pinned_revision: activeRevision,
  required_revision: requiredRevision,
  revision_transition: null,
  created_at: NOW,
  updated_at: NOW,
  admitted_at: NOW,
  started_at: NOW,
  finished_at: null,
  etag: ETAG_A,
} as const;

const artifactBase = {
  project_id: "project-fixture-1",
  run_id: "run-fixture-1",
  display_name: "Deterministic artifact",
  summary: "A deterministic artifact produced by the fixture run.",
  byte_size: 128,
  produced_revision: successorRevision,
  membership_revisions: [successorRevision],
  content_sha256: A,
  selected: true,
  promoted: true,
  release_enabled: true,
  compatibility: {
    execution_modes: ["self-deployed"],
    harness_ids: ["codex"],
    base_model_refs: ["open-models/research-model-fixture-1"],
  },
  lineage: {
    method_id: "reference_text_memory",
    job_id: "job-fixture-1",
    source_dataset_ids: ["dataset-fixture-1"],
    source_artifact_ids: [],
  },
  scores: [{ name: "quality", value: 0.8 }],
  created_at: NOW,
} as const;

export const CONTRACT_FIXTURE_V1 = {
  version: {
    schema_version: "1",
    api_name: "openevo-desktop-local-api",
    preferred_major: 1,
    supported_majors: [1],
    openapi_sha256: OPENAPI_DIGEST,
    build_version: "1.0.0-test.1",
    source_commit: "dabbfec3",
    build_channel: "test",
    provider_kind: "contract_simulator",
    feature_flags: ["remote_profiles", "operation_events", "artifact_inspection", "maintenance"],
  },
  bootstrap: {
    schema_version: "1",
    endpoint: "http://127.0.0.1:43117",
    session_token: "fixture-desktop-session-token-0000000000000001",
    negotiated_contract: {
      major: 1,
      openapi_sha256: OPENAPI_DIGEST,
      provider_kind: "contract_simulator",
      feature_flags: ["remote_profiles", "operation_events", "artifact_inspection", "maintenance"],
    },
  },
  health: {
    service: "openevo-sidecar",
    status: "ok",
    protocol: "openevo-native-sidecar-v1",
    instance_id: "1".repeat(32),
    instance_proof: A,
  },
  error: {
    schema_version: "1",
    request_id: "request-fixture-1",
    code: "project_not_ready",
    http_status: 409,
    message: "The project is not ready.",
    severity: "blocking",
    category: "project",
    retryable: true,
    repair_action: "openevo_can_retry",
    next_action: "Retry after project validation succeeds.",
    details: { field_issues: [], conflicts: [{ resource_type: "project", resource_id: "project-fixture-1" }] },
    logs_ref: "logs-fixture-1",
  },
  unsupportedVersionError: {
    schema_version: "1",
    request_id: "request-fixture-426",
    code: "contract_version_unsupported",
    http_status: 426,
    message: "No compatible Desktop Local API version is available.",
    severity: "blocking",
    category: "contract",
    retryable: false,
    repair_action: "unsupported",
    next_action: "Update OpenEvo Desktop.",
    details: { field_issues: [], conflicts: [] },
    logs_ref: null,
  },
  cursorExpiredError: {
    schema_version: "1",
    request_id: "request-fixture-cursor",
    code: "event_cursor_expired",
    http_status: 410,
    message: "The event cursor has expired.",
    severity: "warning",
    category: "contract",
    retryable: true,
    repair_action: "openevo_can_retry",
    next_action: "Reload snapshots before reconnecting.",
    details: { field_issues: [], conflicts: [] },
    logs_ref: null,
  },
  profile: {
    schema_version: "1",
    profile_id: "profile-fixture-1",
    name: "Research GPU",
    host: "gpu.example.test",
    port: 22,
    user: "researcher",
    authentication_kind: "ssh_agent",
    credential_slots: [],
    proxy: { http_url: "http://proxy.example.test:8080", https_url: null, no_proxy: ["localhost"] },
    connection_state: "connected",
    host_key_fingerprint: "SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    etag: ETAG_A,
    created_at: NOW,
    updated_at: NOW,
  },
  workspaceImport: {
    import_id: "workspace-import-fixture-1",
    content_sha256: C,
    byte_size: 1_024,
    entry_count: 1,
    extracted_byte_size: 128,
  },
  project: {
    schema_version: "1",
    project_id: "project-fixture-1",
    name: "Protein Design",
    profile_id: "profile-fixture-1",
    task: { title: "Design task", objective: "Produce and validate a candidate." },
    source: { kind: "scratch", display_name: "New workspace", import_ref: null },
    execution: {
      mode: "self-deployed",
      capture_mode: "transcript",
      token_level_metrics_available: false,
      codex_model: null,
      reasoning_effort: null,
      hf_model: "open-models/research-model-fixture-1",
    },
    evolution: {
      targets: {
        text_memory: { enabled: true, method: "reference_text_memory", config: { max_records: 100 } },
        skill_bundle: { enabled: false, method: null, config: {} },
      },
    },
    evolution_configuration_state: "configured",
    state: "active",
    remote: {
      core_project_id: "project-fixture-1",
      status: "ready",
      active_revision: activeRevision,
      registry_digest: B,
      model_preparation: {
        model_ref: "open-models/research-model-fixture-1",
        status: "ready",
        downloaded_bytes: 1_024,
        total_bytes: 1_024,
        error: null,
        updated_at: NOW,
      },
      observed_at: NOW,
      etag: ETAG_B,
    },
    etag: ETAG_B,
    created_at: NOW,
    updated_at: NOW,
  },
  operation: {
    schema_version: "1",
    operation_id: "operation-fixture-1",
    operation_kind: "bootstrap",
    state: "running",
    resource: { resource_type: "project", resource_id: "project-fixture-1" },
    progress: { current: 2, total: 4, label: "Verifying remote Core" },
    checks: [
      {
        check_id: "core.install",
        label: "Core installation",
        status: "passed",
        summary: "Verified installation is available.",
        repair_action: "none",
      },
    ],
    result: null,
    error: null,
    created_at: NOW,
    started_at: NOW,
    finished_at: null,
    etag: ETAG_A,
  },
  operationLog: {
    log_id: "local-log-fixture-1",
    occurred_at: NOW,
    level: "info",
    source: "connection",
    message: "The remote Core connection is ready.",
    code: "connection_ready",
  },
  runSummary,
  run: { ...runSummary, attempts: [attempt] },
  queuedRunSummary: {
    ...runSummary,
    id: "run-fixture-queued",
    status: "queued",
    queued_reason: {
      code: "required_revision_uncommitted",
      summary: "The required revision is not active yet.",
      retry_after_seconds: 5,
    },
    current_attempt_id: null,
    current_attempt: null,
    attempt_count: 0,
    pinned_revision: null,
    required_revision: {
      revision: successorRevision,
      reachable_from_revision_id: activeRevision.id,
      relation: "successor",
    },
    revision_transition: revisionTransition,
    admitted_at: null,
    started_at: null,
  },
  timeline: {
    id: "timeline-fixture-1",
    run_id: "run-fixture-1",
    attempt_id: "attempt-fixture-1",
    sequence: 7,
    service_id: "service-control-fixture-1",
    phase: "execution",
    status: "running",
    title: "Science task",
    message: "The task is running against the pinned revision.",
    occurred_at: NOW,
    artifact_ids: [],
    content_sha256: A,
    error: null,
  },
  log: {
    id: "log-fixture-1",
    sequence: 8,
    occurred_at: NOW,
    stream: "agent",
    level: "info",
    message: "Task execution started.",
    run_id: "run-fixture-1",
    attempt_id: "attempt-fixture-1",
    service_id: "service-control-fixture-1",
    content_sha256: B,
  },
  context: {
    schema_version: "1",
    run_id: "run-fixture-1",
    project_id: "project-fixture-1",
    project_snapshot: snapshot("project", A),
    task_snapshot: snapshot("task", B),
    workspace_snapshot: snapshot("workspace", C),
    status: "running",
    queued_reason: null,
    current_attempt_id: attempt.id,
    current_attempt: attempt,
    attempt_count: 1,
    current_error: null,
    pinned_revision: activeRevision,
    required_revision: requiredRevision,
    revision_transition: null,
    registry_digest: B,
    execution_mode: "self-deployed",
    capture_mode: "transcript",
    created_at: NOW,
    updated_at: NOW,
    admitted_at: NOW,
    started_at: NOW,
    finished_at: null,
    etag: ETAG_A,
    token_level_metrics_available: false,
    artifacts: [
      {
        artifact_id: "artifact-memory-fixture-1",
        artifact_type: "text_memory",
        target_id: "text_memory",
        revision: activeRevision,
      },
    ],
    adapters: [],
  },
  artifacts: [
    {
      ...artifactBase,
      id: "artifact-memory-fixture-1",
      target_id: "text_memory",
      artifact_type: "text_memory",
      metadata: { record_count: 1, source_dataset_ids: ["dataset-fixture-1"] },
    },
    {
      ...artifactBase,
      id: "artifact-skill-fixture-1",
      target_id: "skill_bundle",
      artifact_type: "skill_bundle",
      metadata: { document_count: 1, root_document: "SKILL.md" },
    },
    {
      ...artifactBase,
      id: "artifact-agent-fixture-1",
      target_id: "agent_system",
      artifact_type: "agent_system",
      metadata: { target_path: "AGENTS.md" },
    },
    {
      ...artifactBase,
      id: "artifact-adapter-fixture-1",
      target_id: "parametric_memory",
      artifact_type: "parametric_memory",
      release_enabled: false,
      metadata: {
        adapter_id: "adapter-fixture-1",
        base_model_ref: "open-models/research-model-fixture-1",
        adapter_format: "lora",
      },
    },
  ],
  artifactContent: {
    schema_version: "1",
    artifact_id: "artifact-memory-fixture-1",
    artifact_type: "text_memory",
    artifact_content_sha256: A,
    documents: [
      {
        document_id: "memory",
        display_name: "Task memory",
        relative_path: "memory.md",
        mime_type: "text/markdown",
        content: "# Memory\n\nValidated behavior.",
        content_sha256: "b55fbf2b2178de65f2976cc8ec000129c5220a69268ce1dc145c20cbbf16c60c",
        byte_size: 29,
        truncated: false,
      },
    ],
    total_documents: 1,
    total_utf8_bytes: 29,
    returned_utf8_bytes: 29,
    truncated: false,
  },
  artifactDiff: {
    schema_version: "1",
    artifact_id: "artifact-memory-fixture-1",
    artifact_content_sha256: A,
    previous_artifact_id: "artifact-memory-fixture-0",
    previous_artifact_content_sha256: B,
    document_changes: [{
      kind: "modified",
      old_document: {
        artifact_id: "artifact-memory-fixture-0",
        artifact_content_sha256: B,
        document_id: "memory",
        relative_path: "memory.md",
        content_sha256: B,
      },
      new_document: {
        artifact_id: "artifact-memory-fixture-1",
        artifact_content_sha256: A,
        document_id: "memory",
        relative_path: "memory.md",
        content_sha256: A,
      },
      hunks: [
      {
        old_document: {
          artifact_id: "artifact-memory-fixture-0",
          artifact_content_sha256: B,
          document_id: "memory",
          relative_path: "memory.md",
          content_sha256: B,
        },
        new_document: {
          artifact_id: "artifact-memory-fixture-1",
          artifact_content_sha256: A,
          document_id: "memory",
          relative_path: "memory.md",
          content_sha256: A,
        },
        old_start: 0,
        old_count: 0,
        new_start: 1,
        new_count: 1,
        lines: [{ kind: "added", old_line_number: null, new_line_number: 1, text: "Validated behavior." }],
      },
      ],
    }],
    total_document_changes: 1,
    total_hunks: 1,
    total_lines: 1,
    truncated: false,
  },
  service: {
    id: "service-control-fixture-1",
    display_name: "OpenEvo Core",
    kind: "control",
    status: "running",
    restartable: true,
    status_message: "Core is ready.",
    error: null,
    model_preparation: null,
    updated_at: NOW,
    observed_at: NOW,
    etag: ETAG_B,
  },
  serviceOperation: {
    schema_version: "1",
    id: "core-operation-service-fixture-1",
    kind: "service_restart",
    descriptor: { kind: "service_restart", cancellable: false },
    status: "queued",
    request: {
      kind: "service_restart",
      service_id: "service-control-fixture-1",
      request: { schema_version: "1", reason: "Restart the control service." },
    },
    result: null,
    cancellation: null,
    logs_ref: "core-logs-service-fixture-1",
    created_at: NOW,
    updated_at: NOW,
    observed_at: NOW,
    finished_at: null,
    error: null,
    etag: ETAG_A,
  },
  diagnosticRequest: {
    schema_version: "1",
    scopes: ["project"],
    target: { kind: "project", project_id: "project-fixture-1" },
  },
  diagnostic: {
    schema_version: "1",
    id: "diagnostic-fixture-1",
    status: "running",
    scopes: ["project"],
    target: { kind: "project", project_id: "project-fixture-1" },
    checks: [],
    created_at: NOW,
    updated_at: NOW,
    observed_at: NOW,
    finished_at: null,
    error: null,
    etag: ETAG_B,
  },
  cacheCleanupRequest: {
    schema_version: "1",
    scopes: ["build_artifacts", "completed_runs"],
    older_than_days: 30,
  },
  cacheOperation: {
    schema_version: "1",
    id: "core-operation-cache-fixture-1",
    kind: "cache_cleanup",
    descriptor: { kind: "cache_cleanup", cancellable: false },
    status: "running",
    request: { kind: "cache_cleanup", request: { schema_version: "1", scopes: ["build_artifacts", "completed_runs"], older_than_days: 30 } },
    result: null,
    cancellation: null,
    logs_ref: "core-logs-cache-fixture-1",
    created_at: NOW,
    updated_at: NOW,
    observed_at: NOW,
    finished_at: null,
    error: null,
    etag: ETAG_B,
  },
  capabilities: {
    schema_version: "1",
    project_id: "project-fixture-1",
    project_etag: ETAG_B,
    source: "verified_remote_core",
    registry_verified: true,
    fetched_at: NOW,
    capabilities: {
      schema_version: "1",
      core_version: "1.0.0",
      registry_digest: B,
      evaluated_profile: {
        execution_mode: "self_deployed",
        capture_mode: "transcript",
        harness_id: "codex",
        harness_capabilities: [],
        runtime_capabilities: [],
      },
      targets: [
        {
          target_id: "text_memory",
          display_name: "Text memory",
          description: "Natural-language memory.",
          artifact_type: "text_memory",
          exposure: "desktop",
          maturity: "stable",
          handler_id: "text_memory.handler",
          configured_default_method_id: "reference_text_memory",
          effective_default_method_id: "reference_text_memory",
          configured_default_support: support,
          renderer_kind: "markdown",
          renderer_contract_version: "1",
          contribution_contract_version: "2",
          context_order: 10,
          implementation_identity_digest: A,
          handler_identity_digest: B,
          accepted_methods: [
            {
              method_id: "reference_text_memory",
              implementation_identity_digest: C,
              support,
            },
          ],
          selection_resolvers: [],
          methods: [
            {
              method_id: "reference_text_memory",
              display_name: "Reference text memory",
              description: "Reference implementation.",
              exposure: "desktop",
              maturity: "stable",
              execution_modes: ["self_deployed"],
              capture_modes: ["transcript"],
              supported_harness_ids: ["codex"],
              harness_requirements: [],
              runtime_requirements: [],
              input_bindings: [
                {
                  binding_id: "current_dataset",
                  source: "current_dataset",
                  artifact_type: "dataset",
                  min_count: 1,
                  max_count: null,
                },
              ],
              output_artifact_types: ["text_memory"],
              config_schema_json: '{"additionalProperties":false,"properties":{},"type":"object"}',
              default_config_json: "{}",
              implementation_identity_digest: C,
              support,
            },
          ],
        },
      ],
    },
  },
  validation: {
    schema_version: "1",
    project_id: "project-fixture-1",
    project_etag: ETAG_B,
    registry_digest: B,
    valid: true,
    checks: [{ id: "project.valid", status: "ok", message: "Project validation succeeded.", target_id: null, method_id: null }],
    validated_at: NOW,
  },
  state: {
    schema_version: "1",
    observed_at: NOW,
    contract: { selected_major: 1, desktop_openapi_sha256: OPENAPI_DIGEST, core_openapi_sha256: B, compatible: true },
    execution_mode_capabilities: RELEASE_EXECUTION_MODE_CAPABILITIES_FIXTURE_V1,
    core: {
      state: "online",
      profile_id: "profile-fixture-1",
      active_tunnel: true,
      operation_id: null,
      host_key_review: null,
      core: { contract_version: "1", contract_digest: B, core_version: "0.1.0" },
      failure: null,
    },
    active_project: {
      project_id: "project-fixture-1",
      project_etag: ETAG_B,
      profile_id: "profile-fixture-1",
      connection_state: "ready",
    },
    pending_operation_ids: ["operation-fixture-1"],
  },
} as const;

export const PROFILE_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.profile],
  next_cursor: "profile-cursor-2",
  has_more: true,
} as const;
export const RUN_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.runSummary],
  next_cursor: null,
  has_more: false,
} as const;
export const LOCAL_LOG_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.operationLog],
  next_cursor: null,
  has_more: false,
} as const;
export const REFERENCED_LOG_PAGE_FIXTURE_V1 = {
  schema_version: "1",
  items: [CONTRACT_FIXTURE_V1.log],
  next_cursor: null,
  has_more: false,
  logs_ref: "core-logs-service-fixture-1",
} as const;
export const EVENT_FIXTURE_V1 = {
  schema_version: "1",
  event_id: "event-fixture-7",
  event_name: "desktop.v1.resource.changed",
  occurred_at: NOW,
  sequence: 7,
  data: {
    kind: "resource_changed",
    authority: "core",
    resource: { resource_type: "run", resource_id: "run-fixture-1" },
    change: "updated",
    change_id: "run-change-fixture-7",
    resource_etag: ETAG_A,
    content_sha256: null,
  },
} as const;
